version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 3
    groups:
      composer-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 3
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directories:
      - "/"
      - "/docker/glpi"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 3
    groups:
      docker-minor-and-patch:
        update-types:
          - minor
          - patch
